# 异步编程

## Promise

### 三种状态

- pendding（待定）：初始状态
- fulfilled（已实现）：操作成功
- rejected（已拒绝）：操作失败
- 注意：
  - 只能单向转换：pendding-->fulfilled，pendding-->rejected

### 静态方法

- all：全部 Promise 执行成功，或者任意一个执行失败
- allSettled：执行多个 Promise，不论成功失败，结果全部返回
- any：接受一个 Promise 集合，返回第一个成功者
- race：Promise 集合中，返回最快的 Promise 触发结果
- resolve：返回一个解析过参数的 Promise 对象
- reject：返回一个状态为失败的 Promise 对象

### 原型方法

- prototype.then：返回一个 Promise，最多两个参数，成功和失败后的回调函数
- prototype.catch：返回一个 Promise，并处理拒绝的情况
- prototype.finally：返回一个 Promise,在 Promise 结束时，无论成功还是失败，都执行该回调

补充

### 延迟函数

```js
function delay(fn, delay, context) {
  let defaultDelay = dalay || 5000;
  if (!isFunction(fn)) {
    return {
      run: () => Promise.resolve(),
      cancel: noop,
    };
  }
  let ticket;
  let executed = false;
  return {
    run(...args) {
      return new Promise((resolve, reject) => {
        if (executed === true) {
          return;
        }
        exectued = true;
        ticket = setTimeout(async () => {
          try {
            const res = await fn.apply(context, args);
            resolve(res);
          } catch (err) {
            reject(err);
          } finally {
            clearTimeout(ticket);
          }
        }, defaultDelay);
      });
    },
    cancel: () => {
      clearTimeout(ticket);
    },
  };
}
// 测试
const { run, cancel } = delay(() => {
  return '函数执行结果';
}, 3000);
run().then((result) => {
  console.log('result', result);
});
run().then(() => {
  console.log('多次调用run result：', result);
});
```

### 重试多次

```js
function retry(fun, count, assert = () => false) {
  if (!isFunction(fun)) {
    return Promise.resolve();
  }
  retrurn new Promise(async (resolve,reject)=>{
    let error=null;
    for(let tryCount=1;tryCount<=count;tryCount++){
      try{
        const value=await fun(tryCount);
        if(assert(value,tryCount)){
          return resolve(value);
        }
      }catch(e){
        error=e
      }
    }
    reject(new Error('多次尝试失败'))
  })
}
let index=0;
function create Promise(tryCount){
  console.log('尝试失败',truCount);
  return new Promise((resolve,,reject)=>{
    index++;
    setTimeout(()=>{resolve(index)},1000)
  })
}
retry(createPromise,10,(res)=>{
  return res=5;
}).then(res=>{
  console.log('当前数据:',res)
}).then(e=>{
  console.log('捕获到错误:',e)
})
```

### 异常捕获

```js
Promise.solve('success').then(res=>{
  console.log('res1:',res);
  throw new Error('then error');
  return 'fail';
}).then(res=>{
  console.log('res2:',res)
}).catch(e=>{
  console.log('捕获到Promise 错误：',e)
})
// 或者
window.addEventListener('unhandlerejection',event=>{
  console.error('捕获异常1：',event.reason)
})
window.onunhandledrejection=event=>{
  console.log('捕获异常2：',event.reason)
}
const p1=new Promise((resolve,reject)=>{
  throw new Error('错误')
  resolve(5)
})
```

### 注意点：过早处理reject影响链式调用

```js
const p1= new Promise((resolve,reject)=>{
  reject(5)
})
p1.then(res1=>{
  // 不会执行
  console.log('res1:',res1)
},(rejectResult)=>{
  // 执行
  console.log('处理reject result',rejectResult);
  return rejectResult
}).then(re2=>{
  console.log('res2:',res2)
}).catch(e=>{
  // 不会执行
  console.log('reject 错误',e)
})
```

## Generator 函数/生成器函数

```js
// 是一个普通函数
(function* generator() {} instanceof Function); // true
```

### 特征

- 星号：function 关键字与函数名之间有一个星号
- yield 表达式

### generator 对象

- 定义：generator 函数执行后返回的对象
- 方法：
  - prototype.next()：获取下一个状态
  - prototype.return()：给定的值并结束生成器
  - prototype.throw()：抛出异常

补充

### async 本质

补充

## 基于 Promise 的通用异步方案

### 基于事件通讯的场景

- 与服务端通讯：WebSocket，socketIO，mqtt，SSE 等
- 客户端相互之间：webview 与原生，页面与 iframe，EventEmitter 订阅发布中心等等
- 一发一收：类似于 http 请求，一次发送只期待一次返回的结果
- 单纯的接受。希望接收到服务的信息。比如直播业务，监听礼物消息，主播知道有人打赏了。

### 一发一收

补充
